### ISSUE TITLE
advantage of using react wrappers with mapbox gl?

### ISSUE THREAD

**Issue by kewlspopo** [mapbox/mapbox-react-examples#1]
Hey, I'm looking at your examples and it looks like you're not using any external wrapper library for your mapbox gl. I'm wondering if you know any advantage of using such libraries? did you face any difficulties implementing any mapbox gl features on your react app? thanks

**Comment by tristen** [comment]
Hey @kewlspopo we wrote a blog post to answer that very question! Have a look: https://blog.mapbox.com/mapbox-gl-js-react-764da6cc074a
