### ISSUE TITLE
Update examples with `ReactDOM.render()` for React 18

### ISSUE THREAD

**Issue by pReya** [mapbox/mapbox-react-examples#20]
In multiple examples, a DOM element will be created via `ReactDOM.render()`, which is deprecated in React 18. Would be nice to see a best practice how to solve this in React 18.

**Comment by lcurrit** [comment]
This worked:
import { createRoot } from "react-dom/client";

Inside the features forEach loop:

      // Render a Marker Component on our new DOM node
      createRoot(ref.current).render(
        <Marker onClick={markerClicked} feature={feature} />
      );

**Comment by billThieleMms** [comment]
I'm also struggling with this at the moment. I'm trying to add popups to map markers, following the tooltip example from this repository. Haven't found a way of doing it yet without the depcrecated APIs.

**Comment by yewyewxd** [comment]
Hi @billThieleMms , just to clarify, you want to add markers to the map, and when you hover over those markers, it should show a react tool-tip about the marked place, right?
