### ISSUE TITLE
css reference not found

### ISSUE THREAD

**Issue by nenriquez** [mapbox/mapbox-react-examples#7]
There is references to not loaded css classes. Classes like:

` <div className="toggle txt-s py3 toggle--active-white">{option.name}</div>`

**Comment by tristen** [comment]
👋 @nenriquez can you elaborate? I'm not reproducing the CSS failing in those classes. The CSS that styles based on these classes are here: https://github.com/mapbox/mapbox-react-examples/blob/367088eda50453cbd223484724f623779a5e3d2b/data-overlay/public/index.html#L7

**Comment by nenriquez** [comment]
Hi! @tristen Sorry I just remember that some ui elements had wrong visualization.
