### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_0_react___default.a.createRef is not a function

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [mapbox/mapbox-react-examples#8]
new Application
src/index.js:10
   7 | class Application extends React.Component {
   8 |   mapRef = React.createRef();
   9 | 
> 10 |   constructor(props: Props) {
  11 |     super(props);
  12 |     this.state = {
  13 |       lng: 5,
View compiled
▶ 18 stack frames were collapsed.
Object../src/index.js
src/index.js:54
  51 |   }
  52 | }
  53 | 
> 54 | ReactDOM.render(<Application />, document.getElementById('app'));
  55 | 
  56 | 
  57 | 
View compiled
▶ 6 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by tc33133** [comment]
I was having same issue and changed the react and react-dom versions in the package.json from 15.5 to 16.4. Deleted the package-lock.json and the node_modules directory, then ran npm install and app is working correctly

**Comment by tristen** [comment]
Thanks for reporting @ICanDoAllThingThroughChrist and mentioning what worked for you @tc33133. I  have a PR here that updates those versions 👍
